repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.4
    hooks:
      - id: go-fmt
      - id: go-lint
