steps:
  - name: test
    command:
      - make go-mod-verify
      - make check-fmt
      - make lint
      - make test
    plugins:
      - docker-compose#v3.1.0:
          run: test
          config: .buildkite/docker-compose.yml
